site_name: Eugene's Notes 
site_description: The Things I want to share with you.
site_author: Eugene 
site_url: https://quantum51.top/My_Notes

repo_name: FDAW51/My_Notes
repo_url: https://github.com/FDAW51/My_Notes

theme:     
  name: material
  custom_dir: custom
  language: en
  favicon: assets/favicon.png
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: fontawesome/solid/earth-americas
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Customization     
copyright: Built by <a href="http://github.com/FDAW51">Eugene</a> &copy; 2025 - 2030
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FDAW51 
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/Eugene474361140
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/y-eugene-aa4201374/
  analytics:
    provider: google
    property: G-NE8FKX91SB

extra_css:
  - css/custom.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/katex.min.css


extra_javascript:
  - js/math.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:   # ✅ 启用数学支持
      generic: true

nav:
  - Preface: index.md
  - I Electrodynamics:
      - Preface: ED/Preface.md
      - 1 Introduction to Electrostatics: 
          - Chap 1 Note: ED/Chap01/Note/Note.md
          - Chap 1 Problems: ED/Chap01/Probs/test.md
  - II Algorithms:
      - Preface: Algorithms/Preface.md
      - 4 分冶法(Divide and Conquer):
          - Chap 4 Note: Algorithms/Chap04/Note/Note.md
          - Chap 4 Problems: Algorithms/Chap04/Problems/Problems.md
      

